# Jekyll Config

# Site settings
title: Rise & Thrive
description:
baseurl: '/Report' # the subpath of your site, e.g. /blog
url: 'https://founderland.github.io' # the base hostname & protocol for your site
google_analytics: G-Q749X5MH40
# Build settings
exclude:
  - package.json
  - package-lock.json
  - README.md
  - CNAME
  - tailwind.config.js
  - styleguide.html
  - assets/images/unused
  - assets/styles/input.css
# Plugin settings
#plugins:
#  - jekyll-feed
#  - jekyll-sitemap
